title: Living Life and Leaving Lupus Behind
email: jason.l.crandall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Living Life and Leaving Lupus Behind # add your name or title, this will be displayed at the top
author-pic: J-M-profile.jpg # add your photo
about-author: We are Jason and Megan Crandall, we both have traditional jobs but prefer to spend any time we can out in nature. We currently live in sunny Texas which limits our local excursions when one of you is living with lupus. Managing the symptoms and living life to the max is not always easy, but it is  something that can definitely be done. 

# Contact links
email: Jason.L.Crandall@gmail.com # Add your Email address
# phone: # Add your Phone number
website: # Add your website, do not add http://
# linkedin: # Add your Linkedin handle
github: JCrandall # Add your Github handle
# twitter: n/a # Add your Twitter handle
# facebook: n/a # Add your Facebook handle
# instagram: n/a # Add your Instagram handle
# pinterest: # Add your Pinterest handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: Jason # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
